aws/firelens-datajet

- Dockerfile
- core/ext-types.ts
- examples/validate-http/firelens-datajet.json
- generators/generator-index.ts
- generators/validators/http-generator.ts
- generators/validators/validator-index.ts
- package-lock.json
- package.json
> Http validator

- package-lock.json
- package.json
- tsconfig.json
> Resolve lint

- .dockerignore
- .gitignore
- Dockerfile.executor
- Makefile
- wrappers/executors/fluent-bit-executor.ts
Signed-off-by: Matthew Fala <falamatt@amazon.com>
> Containerjet

- datajets/tcp-datajet.ts
> tcp datajet: add close on error and pause on buffer full

- .dockerignore
- .gitignore
- Dockerfile.executor
- Makefile
- wrappers/executors/fluent-bit-executor.ts
Containerize FireLens Datajet to allow for multiple tests to run in parallel.
To run a test use the following command:
```
make containerjetd
```
or
```
make containerjetit
```
The first runs the container in the background in deamon mode, and the second runs the container attached to the shell process.
> Containerjet c

- datajets/tcp-datajet.ts
> Tcp autopause

- apps/magic-mirror/Dockerfile
- apps/magic-mirror/Dockerfile.scratch
- apps/magic-mirror/magic_mirror.sh
- apps/magic-mirror/readme.md
Signed-off-by: Matthew Fala <falamatt@amazon.com>
> app: magicmirror

- apps/magic-mirror/readme.md
> magicmirror: update documentation

- .gitignore
- Makefile
- core/component-dependencies.ts
- core/ext-types.ts
- core/pipeline-defaults.ts
- core/pipeline.ts
- core/rockefeller.ts
- datajets/file-datajet.ts
- datajets/forward-datajet.ts
- datajets/stdout-datajet.ts
- datajets/tcp-datajet.ts
- examples/fluent-bit-executor-advanced/ecs-metadata.conf
- examples/fluent-bit-executor-advanced/example-log.txt
- examples/fluent-bit-executor-advanced/fb_metrics_parser.conf
- examples/fluent-bit-executor-advanced/firelens-datajet.json
- examples/fluent-bit-executor-advanced/fluent-bit-base.conf
- examples/fluent-bit-executor-advanced/prod-fluent.conf
- generators/basic-generator.ts
- generators/csv-generator.ts
- generators/line-by-line-generator.ts
- generators/reverse-csv-generator.ts
- package.json
- wrappers/executors/fluent-bit-executor.ts
An assortment of features and fixes used in repros
> Many Minor Features and Fixes needed for Repros

- app.ts
- clients/client-index.ts
- clients/s3-client.ts
- package-lock.json
- package.json
Pull firelens datajet configuration files from s3
> clients: add s3 client

- core/pipeline-types.ts
- core/pipeline.ts
- datajets/tcp-datajet.ts
- examples/simple-tests/explicit.json
- generators/explicit-generator.ts
- generators/generator-index.ts
- generators/reverse-csv-generator.ts
add explicit generator, and enhance reverse-csv-generator and tcp-datajet
> Explicit Generator

- package-lock.json
- package.json
> security: update vulnerable packages

- .vscode/settings.json
- examples/advanced/compound-firehose-patched-load-test-matrix/firelens-datajet.json
- examples/advanced/firehose-load-test/firelens-datajet.json
- examples/advanced/simple-tests/basic-file-short.json
- examples/advanced/simple-tests/basic-file-threshold-300mbps.json
- examples/advanced/simple-tests/color-logger.json
- examples/advanced/simple-tests/comparator-validator-trivial.json
- examples/advanced/simple-tests/explicit.json
- examples/advanced/simple-tests/fluent-and-referenced-generator.json
- examples/advanced/tcp-forward-file-input/firelens-datajet.json
- examples/advanced/validate-http/firelens-datajet.json
- examples/generators/example-basic-generator-random.json
- examples/generators/example-basic-generator-uniform.json
- examples/generators/example-color-logger-generator.json
- examples/generators/example-csv-generator.json
- examples/generators/example-explicit-generator.json
- examples/generators/example-file-generator.json
- examples/generators/example-increment-generator.json
- examples/generators/example-reference-generator.json
- examples/readme.md
> examples: fix file generator documentation error

- examples/datajets/example-file-datajet/example-file-datajet-firelens-datajet.json
- examples/datajets/example-file-datajet/example-file-datajet-fluent-bit.conf
- wrappers/executors/fluent-bit-executor.ts
> Documentation datajet

- examples/datajets/example-tcp-datajet/example-tcp-datajet-firelens-datajet.json
- examples/datajets/example-tcp-datajet/example-tcp-datajet-fluent-bit.conf
- wrappers/executors/fluent-bit-executor.ts
> Documentation datajet 2

- Makefile
- package.json
> makefile: update build process

- examples/mocks/mountebank/mountebank-firelens-datajet.json
- examples/mocks/mountebank/mountebank-fluent-bit.conf
- examples/mocks/mountebank/mountebank-with-service-unavailable-exception.json
- examples/mocks/mountebank/mountebank.json
- examples/mocks/mountebank/readme.md
- examples/mocks/mountebank/start_cloudwatch_mock.sh
- examples/mocks/mountebank/stubs.md
> examples: add CloudWatch Logs mountebank example

- apps/firelens-stability/lib/cloud/ecs.ts
- apps/firelens-stability/lib/helpers/start-execution-stages.ts
> firelens-stability: resolve task launch retry issue

- apps/firelens-stability/lib/cloud/ecs.ts
- apps/firelens-stability/templates/golden-path-mountebank-fargate-v01-11-2023/task-definition.json
- apps/firelens-stability/templates/s3-fargate-v04-05-2023/task-definition.json
> Unique log stream

- apps/firelens-stability/check_results.sh
- apps/firelens-stability/execution.json
- apps/firelens-stability/package-lock.json
> Stability 2.31.12.20230911

- apps/firelens-stability/lib/cloud/ecs.ts
- apps/firelens-stability/templates/golden-path-mountebank-fargate-v01-11-2023/task-definition.json
> stability: ECS exec update

- apps/ops-scripts/readme.md
- apps/ops-scripts/registry-usage-helper.cjs
> ops: add linux compatibility and run instructions

- apps/ops-scripts/readme.md
- apps/ops-scripts/registry-usage-helper.cjs
> Ops script

- apps/contribution-report/app.ts
> app: resolve contribution report type check error

- apps/mountebank-mock/mountebank-source/package-lock.json
> mock: remove vm2 security vulnerability

- generators/generator-index.ts
- generators/s3-generator.ts
> generators: add s3 log generator
